<?php
/**
 * @file
 * Main hooks for Islandora Badges.
 */

/**
 * Implements hook_menu().
 */
function islandora_twitter_cards_menu() {
  return array(
    'admin/islandora/tools/twitter_cards' => array(
      'title' => 'Islandora Twitter Cards Configuration',
      'description' => 'Configure Twitter cards.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_twitter_cards_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/*
* Implements hook_islandora_view_object()
*/
function islandora_twitter_cards_islandora_view_object() {
 // first grab the MODS metadata and set all variables
  $object = menu_get_object('islandora_object', 2);
  // Get Title.
  if (!isset($object['MODS'])) {
      return;
     }
  $doc = new DOMDocument();
  $doc->loadXML($object['MODS']->content);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $xpath->query(
    variable_get('islandora_twitter_cards_title_xpath', '/mods:mods/mods:titleInfo/mods:title')
  );
  if ($xpath_results->length == 0) {
    return;
  }
  $title = $xpath_results->item(0)->nodeValue;
  if (!$title) {
    return;
  }

  // Get Abstract
  $doc = new DOMDocument();
  $doc->loadXML($object['MODS']->content);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $xpath->query(
    variable_get('islandora_twitter_cards_abstract_xpath', '/mods:mods/mods:abstract')
  );

  if ($xpath_results->length == 0) {
    $abstract = "";
  }
  else {
    $abstract = $xpath_results->item(0)->nodeValue;
  }

  $pid = $object->id;

  // Get Image path. TO DO: Error handling if no image exists.
  if (in_array('ir:citationCModel', $object->models)) {
        $imageDatastream = "PREVIEW";
  }
  elseif (in_array('ir:thesisCModel', $object->models)) {
    $imageDatastream = "PREVIEW";
  }
  elseif (in_array('islandora:sp_large_image_cmodel', $object->models)) {
    $imageDatastream = "JPG";
  }
  elseif (in_array('islandora:sp_basic_image', $object->models)) {
    $imageDatastream = "MEDIUM_SIZE";
  }
    elseif (in_array('islandora:sp_videoCModel', $object->models)) {
    $imageDatastream = "TN";
  }
  
  $image = "/islandora/object/" . $pid . "/" . $imageDatastream . "/view";

  // Get Twitter user - DELETE DEFAULT WHEN READY
  $twitterUser = variable_get('islandora_twitter_cards_twitter_user');

  // Turns out that Twitter no longer recognizes older card types, so this is the only option.
  $cardType = "summary_large_image";

/*
* Implements drupal_add_html_head()
*/

  $tags = array(
    'Twitter card' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:card',
        'content' => $cardType
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Twitter Title' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:title',
        'content' => $title
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Twitter image' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:image',
        'content' => $image
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Twitter site user' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:site',
        'content' => $twitterUser
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Twitter description' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:description',
        'content' => $abstract 
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

}
