<?php
/**
 * @file
 * Main hooks for Islandora Badges.
 */

/**
 * Implements hook_menu().
 */
function islandora_twitter_cards_menu() {
  return array(
    'admin/islandora/tools/twitter_cards' => array(
      'title' => 'Islandora Twitter Cards',
      'description' => 'Configure Twitter cards.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_twitter_cards_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/*
* Implements hook_islandora_view_object()
*/
function islandora_twitter_cards_islandora_view_object() {
 // first grab the MODS metadata and set all variables
  $object = menu_get_object('islandora_object', 2);
  // Get Title.
  if (!isset($object['MODS'])) {
      return;
     }
  $doc = new DOMDocument();
  $doc->loadXML($object['MODS']->content);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $xpath->query(
    variable_get('islandora_twitter_cards_title_xpath', '/mods:mods/mods:titleInfo/mods:title')
  );
  if ($xpath_results->length == 0) {
    return;
  }
  $title = $xpath_results->item(0)->nodeValue;
  if (!$title) {
    return;
  }

  // Get Abstract
  $doc = new DOMDocument();
  $doc->loadXML($object['MODS']->content);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $xpath->query(
    variable_get('islandora_twitter_cards_abstract_xpath', '/mods:mods/mods:abstract')
  );

  // If there is no Abstract field, use a default message.
//  if ($xpath_results->length <= 1) {
//    $abstract = variable_get('islandora_twitter_cards_no_description', 'No description given.');
//  }
//  else {
    $abstract = $xpath_results->item(0)->nodeValue;
//  }

  $pid = $object->id;

  // Get Image path. TO DO: Error handling if no image exists.
  if (in_array('ir:citationCModel', $object->models)) {
        $image_datastream = variable_get('islandora_twitter_cards_citation_datastream', 'PREVIEW');
  }
  elseif (in_array('ir:thesisCModel', $object->models)) {
    $image_datastream = variable_get('islandora_twitter_cards_thesis_datastream', 'PREVIEW');
  }
  elseif (in_array('islandora:sp_large_image_cmodel', $object->models)) {
   $image_datastream = variable_get('islandora_twitter_cards_largeimage_datastream', 'JPG');
  }
  elseif (in_array('islandora:sp_basic_image', $object->models)) {
   $image_datastream = variable_get('islandora_twitter_cards_basicimage_datastream', 'MEDIUM_SIZE');
  }
  elseif (in_array('islandora:sp_videoCModel', $object->models)) {
   $image_datastream = variable_get('islandora_twitter_cards_video_datastream', 'TN');
  }
  else {
    $image_datastream = "TN";
  }

  global $base_url;
  $image = $base_url . "/islandora/object/" . $pid . "/datastream/" . $image_datastream . "/view";
  $og_url = $base_url . "/islandora/object/" . $pid;
// Check whether the image datastream actually exists..

  $file = $image;
  $file_headers = @get_headers($file);

  if (!$file_headers || strpos($file_headers[0], '404')) {
    $exists = FALSE;
  }
  else {
    $exists = TRUE;
  }
 
// If the datastream does not exist, use the default image path. 
  if (!$exists) {
    $image = $base_url . variable_get('islandora_twitter_cards_noimage', '/sites/all/modules/islandora/images/folder.png');
  }

  // Get Twitter user
  $twitter_user = variable_get('islandora_twitter_cards_twitter_user');

  // Turns out that Twitter no longer recognizes older card types, so this is the only option.
  $card_type = "summary_large_image";

/*
* Implements drupal_add_html_head() to inject the meta tags
*/

  $tags = array(
    'Twitter card' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:card',
        'content' => $card_type
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Twitter Title' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:title',
        'content' => $title
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }


  $tags = array(
    'Facebook Title' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:title',
        'content' => $title
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }


  $tags = array(
    'Twitter image' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:image',
        'content' => $image
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Facebook image' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:image',
        'content' => $image
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }


  $tags = array(
    'Twitter site user' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:site',
        'content' => $twitter_user
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Twitter description' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:description',
        'content' => $abstract 
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Facebook description' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:description',
        'content' => $abstract
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Facebook URL' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:url',
        'content' => $og_url
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $tags = array(
    'Object type' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:type',
        'content' => 'article'
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

  $site_name = variable_get('site_name', 'Islandora');

  $tags = array(
    'Facebook site name' => array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:site_name',
        'content' => $site_name
      )
    )
  );

  foreach ($tags as $key => $val) {
    drupal_add_html_head($val, $key);
  }

}
