<?php
/**
 * @file
 * Main hooks for Islandora Badges.
 */

/**
 * Implements hook_menu().
 */
function islandora_twitter_cards_menu() {
  return array(
    'admin/islandora/tools/twitter_cards' => array(
      'title' => 'Islandora Twitter Cards Configuration',
      'description' => 'Configure Twitter cards.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_twitter_cards_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/* To do: 
* Grab content model
* Choose twitter card type based on content model?
* Pick image datastream based on content model anyway
*/

 // first grab the MODS metadata and set all variables
  $object = menu_get_object('islandora_object', 2);
  // Get Title.
  if (!isset($object['MODS'])) {
      return;
     }
  $doc = new DOMDocument();
  $doc->loadXML($object['MODS']->content);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $xpath->query(
    variable_get('islandora_twitter_cards_title_xpath', '/mods:mods/mods:titleInfo/mods:title')
  );
  if ($xpath_results->length == 0) {
    return;
  }
  $title = $xpath_results->item(0)->nodeValue;
  if (!$title) {
    return;
  }
  
  // Get Abstract
  $doc = new DOMDocument();
  $doc->loadXML($object['MODS']->content);
  $xpath = new DOMXPath($doc);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_results = $xpath->query(
    variable_get('islandora_twitter_cards_abstract_xpath', '/mods:mods/mods:abstract')
  );
  if ($xpath_results->length == 0) {
    return;
  }
  $abstract = $xpath_results->item(0)->nodeValue;
  
  // Get Image path
  if (in_array('ir:citationCModel', $object->models)) {
        $imageDatastream = "PREVIEW";
  }
  elseif (in_array('ir:thesisCModel', $object->models)) {
    $imageDatastream = "PREVIEW";
  }
  elseif (in_array('islandora:sp_large_image_cmodel', $object->models)) {
    $imageDatastream = "JPG";
  }
  elseif (in_array('islandora:sp_basic_image', $object->models)) {
    $imageDatastream = "MEDIUM_SIZE";
  }
    elseif (in_array('islandora:sp_videoCModel', $object->models)) {
    $imageDatastream = "TN";
  }
  
  $image = "/islandora/object/" . $pid . "/" . $imageDatastream . '/view';
  
  // Get Twitter user
  $twitterUser = variable_get('islandora_twitter_cards_twitter_user');
  
  // Get card type - turns out that this is the only option
  $cardType = "summary_large_image";

/*
 * Implements hook_html_head_alter
 */
/* First we'll test the other one.
function template_html_head_alter(&$head_elements) {
  
  
  // Add the requisite Twitter meta tags to <head>
  $head_elements = array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array('name' => 'twitter:card', 'content' => $cardType),
    '#weight' => -1001,
  );
}
*/





/* To do:
Here's the set of meta tags:
'
<meta name="twitter:card" content="' . $cardType . '">
<meta name="twitter:site" content="' . $twitterUser . '">
<meta name="twitter:title" content="' . $title . '">
<meta name="twitter:description" content="' . $abstract . '">
<meta name="twitter:image" content="' . $imageLink . '">'

Add config stuff, including option to change the type of card
Figure out how to grab an image for non-image types of content
Figure out which hook to use to interrupt the theme
*/

/* FIRST: pull data from the form
* THEN: pull data from the object
* Then, execute the stuff below.
*/


/*
* Implements drupal_add_html_head
*/
$cardTypeElement = array(
  '#tag' => 'meta', // The #tag is the html tag - 
  '#attributes' => array( // Set up an array of attributes inside the tag
    'name' => 'twitter:card', 
    'content' => $cardType,
  ),
);
$siteElement = array(
  '#tag' => 'meta', // The #tag is the html tag - 
  '#attributes' => array( // Set up an array of attributes inside the tag
    'name' => 'twitter:site', 
    'content' => $twitterUser,
  ),
);
$titleElement = array(
  '#tag' => 'meta', // The #tag is the html tag - 
  '#attributes' => array( // Set up an array of attributes inside the tag
    'name' => 'twitter:title', 
    'content' => $title,
  ),
);
$descElement = array(
  '#tag' => 'meta', // The #tag is the html tag - 
  '#attributes' => array( // Set up an array of attributes inside the tag
    'name' => 'twitter:description', 
    'content' => $abstract,
  ),
);
$imageElement = array(
  '#tag' => 'meta', // The #tag is the html tag - 
  '#attributes' => array( // Set up an array of attributes inside the tag
    'name' => 'twitter:image', 
    'content' => $image,
  ),
);

drupal_add_html_head($cardTypeElement);
drupal_add_html_head($siteElement);
drupal_add_html_head($titleElement);
drupal_add_html_head($descElement);
drupal_add_html_head($imageElement);
